import{a as w,S,i as c}from"./assets/vendor-KnZd4sWe.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",q="49128328-9f71e16c7708b61d93c4a93f1";async function f(o,r=1){const s={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:r};return(await w.get(v,{params:s})).data}const m=document.querySelector(".gallery");let P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function $(){m.innerHTML=""}function y(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:i,comments:b,downloads:L})=>`
            <li class="gallery-item">
                <a href="${a}">
                    <img src="${s}" alt="${e}" loading="lazy" />
                </a>
                <div class="info">
                    <p><b>Likes:</b> ${t}</p>
                    <p><b>Views:</b> ${i}</p>
                    <p><b>Comments:</b> ${b}</p>
                    <p><b>Downloads:</b> ${L}</p>
                </div>
            </li>
        `).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function O(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const h=document.querySelector(".search-form"),E=h.querySelector("input"),d=document.querySelector(".load-more");let n=1,l="",u=1;h.addEventListener("submit",async o=>{if(o.preventDefault(),l=E.value.trim(),n=1,l===""){c.error({message:"Please enter a search term!"});return}$(),d.style.display="none",p();try{const r=await f(l,n);r.hits.length===0?c.warning({message:"Sorry, no images found. Try another query!"}):(y(r.hits),u=Math.ceil(r.totalHits/40),n<u&&(d.style.display="block"))}catch{c.error({message:"Something went wrong. Please try again."})}finally{g()}});d.addEventListener("click",async()=>{n+=1,p();try{const o=await f(l,n);y(o.hits),n>=u&&(d.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."})),O()}catch{c.error({message:"Something went wrong. Please try again."})}finally{g()}});
//# sourceMappingURL=index.js.map
